changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: Security
      labels:
        - security
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Dependencies
      labels:
        - dependencies
    - title: Documentation and maintenance
      labels:
        - documentation
        - maintenance
    - title: Other changes
      labels:
        - '*'
